export const EXCHS = [
  {id:'binance',name:'Binance',logo:'🟡',color:'#F0B90B',vol:'$24.1B',maker:'0.1%',taker:'0.1%',pairs:1400,
   coins:['BTC','ETH','BNB','SOL','XRP','DOGE','ADA','AVAX','DOT','MATIC','LINK','UNI','LTC','BCH','ETC','ATOM','FIL','ICP','APT','ARB','OP','PEPE','SHIB','WLD','SUI'],
   passphrase:false},
  {id:'okx',name:'OKX',logo:'⚫',color:'#eee',vol:'$8.3B',maker:'0.08%',taker:'0.1%',pairs:920,
   coins:['BTC','ETH','OKB','SOL','XRP','DOGE','ADA','AVAX','DOT','MATIC','LINK','UNI','LTC','TON','APT','SUI','ARB','OP','TRX','NEAR'],
   passphrase:true},
  {id:'bybit',name:'Bybit',logo:'🔵',color:'#2B6BF3',vol:'$6.4B',maker:'0.1%',taker:'0.1%',pairs:720,
   coins:['BTC','ETH','SOL','XRP','DOGE','BNB','ADA','AVAX','DOT','MATIC','LINK','LTC','NEAR','APT','SUI','OP','ARB','TON','PEPE'],
   passphrase:false},
  {id:'kucoin',name:'KuCoin',logo:'🟢',color:'#23AF91',vol:'$3.6B',maker:'0.1%',taker:'0.1%',pairs:820,
   coins:['BTC','ETH','KCS','SOL','XRP','DOGE','ADA','AVAX','DOT','MATIC','LINK','UNI','LTC','NEAR','APT','ICP','ALGO','VET','EGLD','ROSE'],
   passphrase:true},
  {id:'gate',name:'Gate.io',logo:'🔴',color:'#E40C5B',vol:'$2.2B',maker:'0.2%',taker:'0.2%',pairs:1600,
   coins:['BTC','ETH','SOL','XRP','DOGE','BNB','ADA','AVAX','DOT','MATIC','LINK','UNI','LTC','NEAR','ARB','OP','SUI','APT','PEPE','WLD'],
   passphrase:false},
  {id:'mexc',name:'MEXC',logo:'🟣',color:'#7B2D8B',vol:'$1.9B',maker:'0%',taker:'0.05%',pairs:2100,
   coins:['BTC','ETH','SOL','XRP','DOGE','BNB','ADA','AVAX','DOT','MATIC','PEPE','FLOKI','BONK','WIF','BOME','MEME','ORDI','SATS','RATS','CATS'],
   passphrase:false},
  {id:'htx',name:'HTX (Huobi)',logo:'🔷',color:'#2263CF',vol:'$1.5B',maker:'0.2%',taker:'0.2%',pairs:620,
   coins:['BTC','ETH','HT','SOL','XRP','DOGE','BNB','ADA','AVAX','DOT','MATIC','LTC','LINK','TRX','NEAR'],
   passphrase:false},
  {id:'coinbase',name:'Coinbase Pro',logo:'🔵',color:'#1652F0',vol:'$4.1B',maker:'0.4%',taker:'0.6%',pairs:410,
   coins:['BTC','ETH','SOL','XRP','DOGE','ADA','AVAX','DOT','MATIC','LINK','UNI','LTC','ATOM','ALGO','CRV','AAVE'],
   passphrase:false},
  {id:'kraken',name:'Kraken',logo:'🦑',color:'#5741D9',vol:'$1.8B',maker:'0.16%',taker:'0.26%',pairs:340,
   coins:['BTC','ETH','SOL','XRP','ADA','DOT','MATIC','LINK','LTC','ATOM','ALGO','DASH','XMR','ETC','ZEC'],
   passphrase:false},
  {id:'bitget',name:'Bitget',logo:'💎',color:'#00B8A9',vol:'$2.8B',maker:'0.1%',taker:'0.1%',pairs:780,
   coins:['BTC','ETH','BGB','SOL','XRP','DOGE','BNB','ADA','AVAX','DOT','MATIC','LINK','LTC','APT','SUI','ARB','OP','TON','NEAR','PEPE'],
   passphrase:true},
];

export const COINS = [
  {sym:'BTC',ico:'₿',name:'Bitcoin'},
  {sym:'ETH',ico:'Ξ',name:'Ethereum'},
  {sym:'BNB',ico:'◈',name:'BNB'},
  {sym:'SOL',ico:'◎',name:'Solana'},
  {sym:'XRP',ico:'✕',name:'XRP'},
  {sym:'DOGE',ico:'Ð',name:'Dogecoin'},
  {sym:'ADA',ico:'₳',name:'Cardano'},
  {sym:'AVAX',ico:'▲',name:'Avalanche'},
  {sym:'DOT',ico:'●',name:'Polkadot'},
  {sym:'MATIC',ico:'⬡',name:'Polygon'},
  {sym:'LINK',ico:'⬡',name:'Chainlink'},
  {sym:'UNI',ico:'🦄',name:'Uniswap'},
  {sym:'LTC',ico:'Ł',name:'Litecoin'},
  {sym:'BCH',ico:'Ƀ',name:'Bitcoin Cash'},
  {sym:'ETC',ico:'Ξ',name:'Ethereum Classic'},
  {sym:'ATOM',ico:'⚛',name:'Cosmos'},
  {sym:'FIL',ico:'⬡',name:'Filecoin'},
  {sym:'ICP',ico:'∞',name:'Internet Computer'},
  {sym:'APT',ico:'◉',name:'Aptos'},
  {sym:'ARB',ico:'◈',name:'Arbitrum'},
  {sym:'OP',ico:'🔴',name:'Optimism'},
  {sym:'NEAR',ico:'◎',name:'NEAR'},
  {sym:'SUI',ico:'💧',name:'Sui'},
  {sym:'TON',ico:'💎',name:'TON'},
  {sym:'TRX',ico:'⬡',name:'TRON'},
  {sym:'PEPE',ico:'🐸',name:'Pepe'},
  {sym:'SHIB',ico:'🐕',name:'Shiba Inu'},
  {sym:'FLOKI',ico:'⚡',name:'Floki'},
  {sym:'BONK',ico:'🐕',name:'Bonk'},
  {sym:'WIF',ico:'🐩',name:'dogwifhat'},
  {sym:'BOME',ico:'📚',name:'Book of Meme'},
  {sym:'MEME',ico:'😂',name:'Memecoin'},
  {sym:'ORDI',ico:'◈',name:'Ordinals'},
  {sym:'SATS',ico:'₿',name:'SATS'},
  {sym:'WLD',ico:'🌍',name:'Worldcoin'},
  {sym:'ALGO',ico:'◈',name:'Algorand'},
  {sym:'VET',ico:'✓',name:'VeChain'},
  {sym:'EGLD',ico:'⬡',name:'MultiversX'},
  {sym:'ROSE',ico:'🌹',name:'Oasis'},
  {sym:'XMR',ico:'⬡',name:'Monero'},
  {sym:'ZEC',ico:'Ƶ',name:'Zcash'},
  {sym:'DASH',ico:'◈',name:'Dash'},
  {sym:'AAVE',ico:'👻',name:'Aave'},
  {sym:'CRV',ico:'⬡',name:'Curve'},
  {sym:'MKR',ico:'◈',name:'Maker'},
  {sym:'COMP',ico:'◈',name:'Compound'},
  {sym:'SNX',ico:'◈',name:'Synthetix'},
  {sym:'GRT',ico:'◈',name:'The Graph'},
  {sym:'LDO',ico:'◈',name:'Lido DAO'},
  {sym:'RPL',ico:'◈',name:'Rocket Pool'},
  {sym:'SAND',ico:'⬡',name:'The Sandbox'},
  {sym:'MANA',ico:'◈',name:'Decentraland'},
  {sym:'AXS',ico:'⚔',name:'Axie Infinity'},
  {sym:'ENJ',ico:'◈',name:'Enjin Coin'},
  {sym:'GALA',ico:'⬡',name:'Gala'},
  {sym:'IMX',ico:'◈',name:'Immutable X'},
  {sym:'FLOW',ico:'◈',name:'Flow'},
  {sym:'XTZ',ico:'Ꜩ',name:'Tezos'},
  {sym:'EOS',ico:'⬡',name:'EOS'},
  {sym:'THETA',ico:'Θ',name:'Theta'},
  {sym:'HBAR',ico:'ℏ',name:'Hedera'},
  {sym:'INJ',ico:'◈',name:'Injective'},
  {sym:'SEI',ico:'◈',name:'Sei'},
  {sym:'TIA',ico:'◈',name:'Celestia'},
  {sym:'JTO',ico:'◈',name:'Jito'},
  {sym:'PYTH',ico:'🐍',name:'Pyth Network'},
  {sym:'JUP',ico:'♃',name:'Jupiter'},
  {sym:'STRK',ico:'◈',name:'Starknet'},
  {sym:'EIGEN',ico:'⬡',name:'EigenLayer'},
  {sym:'ENA',ico:'◈',name:'Ethena'},
  {sym:'W',ico:'◈',name:'Wormhole'},
  {sym:'ONDO',ico:'◈',name:'Ondo Finance'},
  {sym:'RENDER',ico:'◈',name:'Render'},
  {sym:'FET',ico:'◈',name:'Fetch.ai'},
  {sym:'AGIX',ico:'◈',name:'SingularityNET'},
  {sym:'TAO',ico:'◈',name:'Bittensor'},
  {sym:'PRIME',ico:'◈',name:'Parallel'},
  {sym:'BLUR',ico:'◈',name:'Blur'},
  {sym:'NFT',ico:'◈',name:'APENFT'},
  {sym:'RATS',ico:'🐀',name:'Rats'},
  {sym:'CATS',ico:'🐱',name:'Cats'},
];
